Compare shodan censys
TopologyMapping/network-security pull request #29
Opened 2023-12-18 12:30 UTC by Francisco-aragao

Fix scripts to filter and analyze ips, ports and scanning frequencies for shodan and censys.

2024-09-30 19:49 UTC, cunha requested changes

2024-09-30 19:49 UTC, cunha commented on analysisDataset/analysis_shodan_censys_data.py
> +"""
Please follow the standard for creating docstrings: https://peps.python.org/pep-0257/

2024-09-30 19:49 UTC, cunha commented on analysisDataset/analysis_shodan_censys_data.py
> +        self.attributes_collected: list[str] = [""]
Why add an empty element to the list? If an empty list does not work, write a comment mentioning why. (Or try to refactor the code such that an empty list works.)

2024-09-30 19:49 UTC, cunha commented on analysisDataset/analysis_shodan_censys_data.py
> +        cpe_list: list | None,
Why do we need `None`? Can't we just use an empty list to capture cases where there is no associated CPE?

2024-09-30 19:49 UTC, cunha commented on analysisDataset/analysis_shodan_censys_data.py
> +        if (ip) not in self.cpe_by_ip:
Remove parenthesis around `(ip)`.

2024-09-30 19:49 UTC, cunha commented on analysisDataset/analysis_shodan_censys_data.py
> +            (keysDict) for keysDict in self.attributes_collected
Spurious parentheses.

2024-10-18 19:37 UTC, Francisco-aragao commented on analysisDataset/analysis_shodan_censys_data.py
> +            (keysDict) for keysDict in self.attributes_collected
fixed -> removed parenthesis

2024-10-18 19:37 UTC, Francisco-aragao commented on analysisDataset/analysis_shodan_censys_data.py
> +        if (ip) not in self.cpe_by_ip:
fixed -> removed parenthesis

2024-10-18 19:37 UTC, Francisco-aragao commented on analysisDataset/analysis_shodan_censys_data.py
> +        cpe_list: list | None,
fixed -> Changed 'None' to empty list

2024-10-18 19:37 UTC, Francisco-aragao commented on analysisDataset/analysis_shodan_censys_data.py
> +        self.attributes_collected: list[str] = [""]
fixed -> empty element ('') was irrelevant. Removed

2024-10-18 19:37 UTC, Francisco-aragao commented on analysisDataset/analysis_shodan_censys_data.py
> +"""
fixed -> docstrings

2024-10-19 18:41 UTC, closed without merging