add:framework-zap
TopologyMapping/network-security pull request #42
Opened 2024-09-05 17:42 UTC by Sacramento-20

Pull request created, all basic information about the program's flow can be found in the README.

2024-12-23 21:37 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/copy.sh
> +    exit 1
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:37 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/copy.sh
> +# Verifica se foi passado somente 1 argumento
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:38 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/copy.sh
> +#!/bin/bash
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:38 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/copy.sh
> +for file in "$ORIGEM"/*.json; do
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:38 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/Makefile
> +generate_key:
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:39 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/README.md
> +Apenas dois atributos são opcionais: a URL da página de login e o título do relatório. Se a URL de login não for fornecida, o framework utiliza o spider do ZAP para tentar identificar as URLs da apli
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:39 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/README.md
> +
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:39 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/README.md
> +O servidor web foi projetado para criar uma interface entre o framework e o usuário. Ele roda na porta `8000` e expõe o volume no localhost, permitindo que o usuário visualize os arquivos gerados.
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:40 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/README.md
> +O Pydantic fará o *parser* do arquivo e extrairá os atributos necessários para a criação do contexto. Um exemplo será disponibilizado na raiz do repositório, chamado `example.json`.
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:40 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/README.md
> +docker logs -f authentication_zap_gt_crivo-zaproxy-1
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:40 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/server/dockerfile
> +# Use a imagem oficial do Python como base
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:40 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/requirements.txt
> +annotated-types==0.7.0
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:40 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +import re
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:41 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +    while not (directory_path.exists() and any(directory_path.iterdir())):
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:41 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +    ZAP_PROXY_PORT = 8080
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:41 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +    ZAP_API_KEY = os.getenv("ZAP_API_KEY")
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:41 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +    proxyServerUrl = f"{ZAP_PROXY_ADDRESS}:{ZAP_PROXY_PORT}"
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:42 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/user_data/user_data.py
> +class User(BaseModel):
5cea303cf6b4d5940e66c6bf0bc5b5be248b3da8

2024-12-23 21:42 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/user_data/user_data.py
> +    exclude_urls: List[str] = []
5cea303cf6b4d5940e66c6bf0bc5b5be248b3da8

2024-12-23 21:42 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +    print(user)
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:42 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +    if FLAG_LOGIN == 0:
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:42 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +            time.sleep(DEFAULT_TIME)
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:43 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +    scanid = zap.automation.run_plan(output_yaml, ZAP_API_KEY)
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:43 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +    for id in messageId:
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:43 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +    messageId = []
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:44 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +    # Lembrar que pegar o ultimo ainda é o mais sensato (evitar casos que manda a credencial que queremos, mas de uma forma errada) tem que testar.
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:44 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +                break
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:44 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +                except Exception:
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:44 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +                    time.sleep(1)
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:44 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +            for type, field in elements.items():
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:45 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +        pass
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:45 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/main.py
> +        time.sleep(DEFAULT_TIME)
90537d21ccb7032eb421886042a69dd9c6940108

2024-12-23 21:46 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/elements/elements.py
> +password_regex = r'\b[\w.-]*password[\w.-]*\b'
61c99afdc364f046e2d9cd9d8428360a1c6499d8

2024-12-23 21:46 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/elements/elements.py
> +def filtered_dict(driver, evidence, struct_login):
61c99afdc364f046e2d9cd9d8428360a1c6499d8

2024-12-23 21:46 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/elements/elements.py
> +    if not elements:
61c99afdc364f046e2d9cd9d8428360a1c6499d8

2024-12-23 21:46 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/elements/elements.py
> +            attributes_to_gather = [
61c99afdc364f046e2d9cd9d8428360a1c6499d8

2024-12-23 21:46 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/elements/elements.py
> +    for d in array_elements:
61c99afdc364f046e2d9cd9d8428360a1c6499d8

2024-12-23 21:46 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/elements/elements.py
> +        for _, value in d.items():
61c99afdc364f046e2d9cd9d8428360a1c6499d8

2024-12-23 21:46 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/elements/elements.py
> +        except NoSuchAttributeException:
61c99afdc364f046e2d9cd9d8428360a1c6499d8

2024-12-23 21:46 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/elements/elements.py
> +    if filtered_dictionaries != []:
61c99afdc364f046e2d9cd9d8428360a1c6499d8

2024-12-23 21:46 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/elements/elements.py
> +            for index, element in enumerate(filtered_dictionaries):
61c99afdc364f046e2d9cd9d8428360a1c6499d8

2024-12-23 21:46 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/elements/elements.py
> +    driver.quit()
61c99afdc364f046e2d9cd9d8428360a1c6499d8

2024-12-23 21:47 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/keywords/keywords.py
> +url_words = keywords["valid_urls"]  # valid_urls.txt
61c99afdc364f046e2d9cd9d8428360a1c6499d8

2024-12-23 21:47 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/keywords/regex_words/invalid_urls.txt
> +\b[\w.-]*css[\w.-]*\b
61c99afdc364f046e2d9cd9d8428360a1c6499d8

2024-12-23 21:47 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/autentication/autentication.py
> +    except:
1ab1fa3dbc86cebbb08c5584d35e287f4640673f

2024-12-23 21:47 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/autentication/autentication.py
> +        print("failed to log in !")
1ab1fa3dbc86cebbb08c5584d35e287f4640673f

2024-12-23 21:48 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/context/context.py
> +        if "%40" in text:
299431ef2f5171b6379e32066f9a4852769bca07

2024-12-23 21:48 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/context/context.py
> +
299431ef2f5171b6379e32066f9a4852769bca07

2024-12-23 21:48 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/urls_login/urls_login.py
> +        for palavra in lista_palavras:
57355f0b9b9d5f6d95e67aa8f79e4a983393c412

2024-12-23 21:49 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/copy.sh
> +docker compose exec framework bash -c "mkdir -p $DESTINO && rm -rf $DESTINO/*"
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:50 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/docker-compose.yml
> +      - shared_data:/shared_data
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:50 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/README.md
> +make run DIR="diretório dos arquivos"
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:50 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/Dockerfile
> +CMD sleep 30 && python3 main.py
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:51 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/docker-compose.yml
> +      - ./framework:/app
4ae37b6c01e3ed00b8c4f4d0bdd1e27a86d944eb

2024-12-23 21:51 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/params/params.py
> +def Define_type_authentication(
0f8635db979aecf0bb7ef2bf7596d0e6603d0850

2024-12-23 21:51 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/params/params.py
> +    session_parameters = session_parameters[0]["Parameter"]
0f8635db979aecf0bb7ef2bf7596d0e6603d0850

2024-12-23 21:51 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/params/params.py
> +            name in keywords.password_field_identifiers
0f8635db979aecf0bb7ef2bf7596d0e6603d0850

2024-12-24 16:04 UTC, cunha requested changes
Parei a revisão na metade. Todos os comentários foram fechados com ponteiros para commits muitas vezes não relacionados ao comentário que eu tinha deixado. Se for possível, passe nos comentários que eu tinha feito elaborando as respostas ou fazendo modificações para adequar o código.

2024-12-24 16:04 UTC, cunha commented on Authentication_ZAP_GT_CRIVO/framework/context/context.py
> +        if "%40" in text:
Chega.

2024-12-24 21:07 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/copy.sh
> +# Verifica se foi passado somente 1 argumento
all scripts and documentation have been translated into English

2024-12-24 21:15 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/context/context.py
> +    """
i forgot to use black in the code, now its done.

2024-12-24 21:21 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/keywords/regex_words/invalid_urls.txt
> +\b[\w.-]*css[\w.-]*\b
The suggestions were added; they were not included initially because they were not captured in previous tests.

```suggestion
\b[\w.-]*pdf[\w.-]*\b
\b[\w.-]*jpg[\w.-]*\b
```

2024-12-24 22:54 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/framework/autentication/autentication.py
> +    except:
The function handles cases where the element cannot be found. If one of the elements corresponding to the form is incompatible, it will refresh the page to apply other elements during authentication.

2024-12-24 22:58 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/copy.sh
> +docker compose exec framework bash -c "mkdir -p $DESTINO && rm -rf $DESTINO/*"
I couldn't implement the functionality satisfactorily.

2024-12-24 22:59 UTC, Sacramento-20 commented on Authentication_ZAP_GT_CRIVO/copy.sh
> +for file in "$ORIGEM"/*.json; do
I thought about doing it the way you suggested, as we discussed, but it didn't work as well as the current approach, where the user provides the folder with the information and the script copies it to the volume.

2025-01-08 21:49 UTC, merged