feat: add files for distributed_classification
TopologyMapping/network-security pull request #48
Opened 2024-12-18 00:05 UTC by Francisco-aragao

Files for LLM script classification

2024-12-21 18:42 UTC, cunha requested changes
The modularization is good, I've just left some style suggestions. The major comment I have is that we should add type hints to functions and major variables.

2024-12-21 18:42 UTC, cunha commented on LLM_classification/metasploit.py
> +    match = re.search(r"'Privileged'\s*=>\s*(true|false)\s*,", content, re.IGNORECASE)
This will compile the regex every time the function is called. Consider compiling the regex once (a module variable is OK here).

2024-12-21 18:42 UTC, cunha commented on LLM_classification/metasploit.py
> +        return match.group(1)
I prefer using named captures: https://docs.python.org/3/howto/regex.html#non-capturing-and-named-groups

2024-12-21 18:42 UTC, cunha commented on LLM_classification/metasploit.py
> +    """Extract CVE identifiers from a Metasploit file."""
This Docstring does not help much, as it repeats the name of the function.

2024-12-21 18:42 UTC, cunha commented on LLM_classification/metasploit.py
> +    cve_pattern = re.compile(r"\[\s*'CVE'\s*,\s*'(\d{4}-\d+)'\s*\]")
Compiles the regex every time the function is called.

2024-12-21 18:42 UTC, cunha commented on LLM_classification/metasploit.py
> +    ):  # adding word cve in cve list because the regex dont match it
Move comment into a separate line to avoid the line break inside the `range()`.

2024-12-21 18:42 UTC, cunha commented on LLM_classification/metasploit.py
> +    # content = read_file_with_fallback(metasploit_file)
Remove dead code

2024-12-21 18:42 UTC, cunha commented on LLM_classification/metasploit.py
> +def extract_rank_from_metasploit(metasploit_file):
Please add type hints to all functions; it's a great way to document code.

2024-12-21 18:42 UTC, cunha commented on LLM_classification/metasploit.py
> +    if privileged == "true" and (module == "Exploit" or executes_exploit is True):
Please convert boolean variables to `bool`. Let's avoid `"true"`.

2024-12-21 18:42 UTC, cunha commented on LLM_classification/metasploit.py
> +            # continue
Remove dead code

2024-12-21 18:42 UTC, cunha commented on LLM_classification/metasploit.py
> +    metasploit_info = []
Add type annocations to major variables.

2024-12-21 18:42 UTC, cunha commented on LLM_classification/nmap.py
> +def analysis_nmap_scripts(nuclei_folder, initial_range, final_range):
Rename `nuclei_folder`

2024-12-21 18:42 UTC, cunha commented on LLM_classification/nmap.py
> +    nmap_files = [
This should be sorted to ensure we will always iterate over files in the same order. As-is, it depends on the order in which `os.walk` visits the files.

2024-12-21 18:42 UTC, cunha commented on LLM_classification/nmap.py
> +        file_name = nmap_file.split("/")[-1]
Use something to get the last item in the path name. This may not work on Windows or other operating systems that do not use forward slash as directory separators. It might also not work if there is no slash in the name.

2024-12-21 18:42 UTC, cunha commented on LLM_classification/nmap.py
> +        "discovery" in categorie and "safe" in categorie
Typo in `category`.

2024-12-21 18:42 UTC, cunha commented on LLM_classification/nmap.py
> +    ):  # 'safe' included because there is 'intrusive' codes that receives 'discovery' categorie, even when performs attacks
Move comment to separate line to avoid linebreaks inside the `elif`; wrap comment lines.

2024-12-22 01:52 UTC, Francisco-aragao commented on LLM_classification/utils.py
> +def receive_arguments():
fixed

2024-12-22 01:52 UTC, Francisco-aragao commented on LLM_classification/README.md
> +- ```SCANNER``` is one of the following options: nmap, openvas, nuclei, metasploit.
the scanner is the name of the tool to be classified. Fixed README to be easier to understand.

2024-12-22 01:52 UTC, Francisco-aragao commented on LLM_classification/distributed_classification.py
> +        results["nmap"] = {}
fixed

2024-12-22 01:52 UTC, Francisco-aragao commented on LLM_classification/utils.py
> +LLM = openai.OpenAI(
new LLM class added

2024-12-22 01:52 UTC, Francisco-aragao commented on LLM_classification/requirements.txt
> +annotated-types==0.7.0
added new requirements

2024-12-22 01:52 UTC, Francisco-aragao commented on LLM_classification/utils.py
> +        raise Exception("Arquivo não existe")
new exception raised

2024-12-22 01:53 UTC, Francisco-aragao commented on LLM_classification/metasploit.py
> +    match = re.search(r"'Privileged'\s*=>\s*(true|false)\s*,", content, re.IGNORECASE)
fixed, added variables for compiling the regex

2024-12-22 01:53 UTC, Francisco-aragao commented on LLM_classification/metasploit.py
> +        return match.group(1)
fixed

2024-12-22 01:53 UTC, Francisco-aragao commented on LLM_classification/metasploit.py
> +    """Extract CVE identifiers from a Metasploit file."""
removing bad comments

2024-12-22 01:54 UTC, Francisco-aragao commented on LLM_classification/metasploit.py
> +    cve_pattern = re.compile(r"\[\s*'CVE'\s*,\s*'(\d{4}-\d+)'\s*\]")
fixed the regex

2024-12-22 01:54 UTC, Francisco-aragao commented on LLM_classification/metasploit.py
> +    ):  # adding word cve in cve list because the regex dont match it
fixed

2024-12-22 01:54 UTC, Francisco-aragao commented on LLM_classification/metasploit.py
> +    # content = read_file_with_fallback(metasploit_file)
removed

2024-12-22 01:54 UTC, Francisco-aragao commented on LLM_classification/metasploit.py
> +def extract_rank_from_metasploit(metasploit_file):
fixed

2024-12-22 01:54 UTC, Francisco-aragao commented on LLM_classification/metasploit.py
> +    if privileged == "true" and (module == "Exploit" or executes_exploit is True):
fixed

2024-12-22 01:54 UTC, Francisco-aragao commented on LLM_classification/metasploit.py
> +            # continue
removed

2024-12-22 01:54 UTC, Francisco-aragao commented on LLM_classification/metasploit.py
> +    metasploit_info = []
fixed

2024-12-22 01:54 UTC, Francisco-aragao commented on LLM_classification/nmap.py
> +def analysis_nmap_scripts(nuclei_folder, initial_range, final_range):
renamed

2024-12-22 01:55 UTC, Francisco-aragao commented on LLM_classification/nmap.py
> +    nmap_files = [
fixed, sorted all the lists to ensure the classification order. Thanks!

2024-12-22 01:55 UTC, Francisco-aragao commented on LLM_classification/nmap.py
> +        file_name = nmap_file.split("/")[-1]
fixed, using os.path.basename

2024-12-22 01:55 UTC, Francisco-aragao commented on LLM_classification/nmap.py
> +        "discovery" in categorie and "safe" in categorie
fixed

2024-12-22 01:55 UTC, Francisco-aragao commented on LLM_classification/nmap.py
> +    ):  # 'safe' included because there is 'intrusive' codes that receives 'discovery' categorie, even when performs attacks
fixed

2024-12-23 14:49 UTC, cunha requested changes
Partial comments on some of the files.

2024-12-23 14:49 UTC, cunha commented on LLM_classification/INFO_SPEED.md
> +### How to use the LLM model in a distributed way (SPEED LAB)
This file should not be part of this directory, it is some internal documentation we use (and thus makes less sense to upload it to RNP's git repo).

2024-12-23 14:49 UTC, cunha commented on LLM_classification/INFO_SPEED.md
> +
Instead of listing the machines explicitly, explain what properties are needed for us to run the model. And then discuss why some machines satisfy the requirements while the others don't.

2024-12-23 14:49 UTC, cunha commented on LLM_classification/INFO_SPEED.md
> +```cd /home/all_home/gabriel.cardoso/llama-cpp/build-rpc-cuda/bin/```
We likely need to explain where/how to get `llama-cpp` going; or provide links to its documentation.

2024-12-23 14:49 UTC, cunha commented on LLM_classification/INFO_SPEED.md
> +```./rpc-server -H <ip_rpc> -p <port_rpc>```
Please use Markdown code blocks accordingly. See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

2024-12-23 14:49 UTC, cunha commented on LLM_classification/INFO_SPEED.md
> +- Go to a machine with the model: ex: gorgona1
How do get a "machine with the model"?  Why don't all machines have the model?

2024-12-23 14:49 UTC, cunha commented on LLM_classification/INFO_SPEED.md
> +Ensure that the model is in the path specified in the command above and correctly installed. Also, ensure that the RPC server is running and the machine is available to use the model.
These "ensure" conditions seem a bit arcane.  It would be best to explain what can go wrong so that the user is better informed to troubleshoot issues if any arise.

2024-12-23 14:50 UTC, cunha requested changes
Additional general comments:

* Move code from `LLM_classification` into a more semantically meaningful name, like `group-identification-scripts` or something similar.

* Are we still planning to move the prompts from within `constants.py` into text files?

2024-12-23 18:02 UTC, Francisco-aragao commented on LLM_classification/constants.py
> +PROMPT_WHAT_IS_DETECTED_ATTACK = """
separated prompts in .txt files

2024-12-23 18:04 UTC, Francisco-aragao commented on LLM_classification/constants.py
> +"""
fixed

2024-12-23 18:04 UTC, Francisco-aragao commented on LLM_classification/constants.py
> +    + """
fixed

2024-12-23 18:06 UTC, Francisco-aragao commented on LLM_classification/INFO_SPEED.md
> +### How to use the LLM model in a distributed way (SPEED LAB)
In the end, i removed this file.

2024-12-28 13:32 UTC, cunha requested changes
* Directories `vulnrank` and `shodan` should *not* be part of the PR. Please rebase on top of the main (master) branch: `git rebase -i main`.

* Please rename `catetorie` to `category` in files inside `prompts`.

* Please change the names of files inside the `prompts` directory to make it clear what tool they refer to.  For example, it seems that `modules_info.txt` is related to Metasploit, so we could name it `metasploit_modules_info.txt`.  If a file is relevant for multiple tools, we can use something like `multi_`, or whatever is appropriate.  In other words, it would be better if the relationship between the files, scanning tools, and LLM was clearer from the file name.

* `requirements.txt` is still locking *all* library versions; we should remove the version locks unless strictly necessary.  It also seems to include many libraries that are never directly imported; we should remove all the libraries that are not direct dependencies of our code from the requirements file.

2024-12-28 13:32 UTC, cunha commented on LLM_classification_and_grouping/README.md
> +```python3 verify_code_similarity.py --input <INPUT_FILE> --ip_port <LLM_IP_PORT> --number_of_files_compared <NUMBER_OF_FILES>```
Please use only one backtick for one-line or inline `code` markup. Please use triple backticks only for code *blocks*.

2024-12-28 13:33 UTC, cunha requested changes

2024-12-28 13:33 UTC, cunha commented on LLM_classification_and_grouping/verify_code_similarity.py
> +This module is not useful to be used alone, but is important to use it after calling the function 'compare_similarity_openvas' in the file 'openvas.py' to evaluate the results.
Follow Docstring convention: https://peps.python.org/pep-0257/

2024-12-28 15:24 UTC, cunha requested changes

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +    for key in applications:
Please remove all variables named `key` from the code. This name is meaningless, it does not help with understanding what the code does. Please use variable names that capture meaning.

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +        tokens_key = key.split("_")
Also avoid encoding multiple information in strings by using separators like `_` or `-`; instead create tuples or `dataclasses` (you can freeze dataclasses to use them as dictionary keys) to make code self-documented.

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +                    return key
Please see comment above; use meaningful variable names.

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +            errors_LLM.append(info_to_store)
Catch the two exception types explicitly, and *then* do the catch all and `pass`. Document why we ignore other exceptions.

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +    for cves_key in cves:
Rename `cves_key`.

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +            problems[cves_key][category_subcategory][what_is_detected] = {}
```suggestion
problems = defaultdict(lambda: defaultdict(lambda: defaultdict(dict)))
```

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +            problems[cves_key][category_subcategory][what_is_detected] = {}
But really, is this the best way to organize this information? This is very unyieldly.

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +        CHECK_IF_APPLICATION_NAME_IS_TOO_LONG = len(filtered_tokens_application)
Why is this variable name uppercase?

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +    info_to_store: str,
Use meaningful name

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +                            file_content = read_file_with_fallback(script_name)
It seems like we shouldn't need to read the file again at this point, as the script ID should be already known when we get here.

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +    inverted_dict = dict(organized_grouping)
Why do we need to do this?

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +    with open("./results/grouped_scripts.json", "w") as f:
Refactor hardcoded paths; best is to make them command-line parameters, or if nor possible at least store file paths as constants in a `config.py` module or something.

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +                for entry in data[scan_app]:
Rename `entry` variable into something meaningful

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +                    # if there is no CVE, it is stored as an empty string
Why? It seems like it would be better to just keep an empty list when there are no CVEs, otherwise we need to check for the empty string.

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +                    info_to_store = file_name + " - " + entry["file"]
Avoid encoding multiple pieces of information in a string; this makes it impossible to keep track of what is going on elsewhere in the code.

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +                    info_to_store = file_name + " - " + entry["file"]
Use a tuple, `namedtuple`, or frozen `dataclass`.

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +                    info = classification_info_extracted
```suggestion
```

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +                    info = classification_info_extracted
Just name the variable in the assignment above something short and meaningful (not `info`).

2024-12-28 15:24 UTC, cunha commented on LLM_classification_and_grouping/create_problems.py
> +                    category_subcategory = category + "_" + subcategory
Avoid this.

2024-12-28 15:25 UTC, cunha commented
Please avoid encoding multiple pieces of information in strings by joining with `_` or `-`. Use tuples, `namedtuples`, or frozen `dataclasses` insteadl.

2024-12-28 15:26 UTC, cunha commented
Consider adding type annotations to the code, these work great as documentation (and help coding easier overall by empowering autocomplete).

2024-12-29 00:47 UTC, Francisco-aragao commented on LLM_classification_and_grouping/verify_code_similarity.py
> +    while classified < number_of_files_compared:
Nothing, the objective is just to classify a certain number of files. With more files classified, better are the confidence in the results obtained.

2024-12-29 00:51 UTC, Francisco-aragao commented on LLM_classification_and_grouping/README.md
> +- ```<NUMBER_OF_FILES>``` is the number of files to be compared. If the value is X, then X unique files will be compared with the 'similars' categorie, and X unique files will be compared with the 'm
there are a lot of files, so comparing everything would be very time-consuming. The point is to classify a certain number of files to infer whether the grouping was good. I don't want to classify 3 files for example because the results are very limited, the ideal would be to classify a higher number to have confidence in the results (the default is 500 - 500 is an arbitrary value)

2024-12-29 00:53 UTC, Francisco-aragao commented on LLM_classification_and_grouping/README.md
> +- ```<NUMBER_OF_FILES>``` is the number of files to be compared. If the value is X, then X unique files will be compared with the 'similars' categorie, and X unique files will be compared with the 'm
I will explain this on the readme to be easier to understand the reason

2024-12-29 01:22 UTC, Francisco-aragao commented on LLM_classification_and_grouping/distributed_classification.py
> +    with open(f"./results/{args.output}_classification.json", "w") as f:
Fixed. The idea was just to standardize the classification file names to make it easier during 'create_problems'. Now the code creates a new folder just for the classifications and I store/read all the results in this new folder, avoiding the problem.

2024-12-29 01:26 UTC, Francisco-aragao commented on LLM_classification_and_grouping/README.md
> +```python3 verify_code_similarity.py --input <INPUT_FILE> --ip_port <LLM_IP_PORT> --number_of_files_compared <NUMBER_OF_FILES>```
fixed

2024-12-29 01:26 UTC, Francisco-aragao commented on LLM_classification_and_grouping/verify_code_similarity.py
> +This module is not useful to be used alone, but is important to use it after calling the function 'compare_similarity_openvas' in the file 'openvas.py' to evaluate the results.
fixed

2024-12-29 01:26 UTC, Francisco-aragao commented on LLM_classification_and_grouping/verify_code_similarity.py
> +    )
fixed

2024-12-29 01:26 UTC, Francisco-aragao commented on LLM_classification_and_grouping/verify_code_similarity.py
> +    )
fixed

2024-12-29 01:26 UTC, Francisco-aragao commented on LLM_classification_and_grouping/verify_code_similarity.py
> +        help="Number of files to be compared. Default=500.",
fixed

2024-12-29 01:26 UTC, Francisco-aragao commented on LLM_classification_and_grouping/verify_code_similarity.py
> +        required=False,
fixed

2024-12-29 01:27 UTC, Francisco-aragao commented on LLM_classification_and_grouping/verify_code_similarity.py
> +    cves_unique_files = list(info_op_nvts["unique_files"].keys())
fixed. New name 'main_files'.

2024-12-29 01:27 UTC, Francisco-aragao commented on LLM_classification_and_grouping/distributed_classification.py
> +    )
fixed

2024-12-29 01:27 UTC, Francisco-aragao commented on LLM_classification_and_grouping/distributed_classification.py
> +        "--initialRange", type=int, required=True, help="Initial classification range."
fixed

2024-12-29 17:00 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/utils.py
> +def find_key_by_value(input_dict, value):
I agree with the problem, but i use this function just to find an element in a dict (QOD_VALUES). The dict is constant, there is just 15 elements on it, so the complexity will not be a problem. But I changed to use an inverse mapping.

2024-12-29 17:43 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/constants.py
> +PROMPT_METASPLOIT_POST = (
It's different. I moved the larger prompts and contextual information to the .txt files. In this case, the PROMPT_METASPLOIT_POST contains relatively small information, so I left it in the file itself.

2024-12-29 17:50 UTC, Francisco-aragao commented on LLM_classification_and_grouping/distributed_classification.py
> +        tests_with_no_CVE += NVTS_with_no_CVE
Fixed, but it still classificates different tools at once. The idea is that the process is similar and I can pass multiple tools at once. However, I can also change it to leave only one tool if preferred

2024-12-29 17:50 UTC, Francisco-aragao commented on LLM_classification_and_grouping/distributed_classification.py
> +    return results
fixed

2024-12-29 17:50 UTC, Francisco-aragao commented on LLM_classification_and_grouping/verify_code_similarity.py
> +            break
WOW, that was good. Thanks

2024-12-29 17:50 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/LLM.py
> +        self.LLM = None
fixed

2024-12-29 17:52 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/utils.py
> +        raise FileNotFoundError()
fixed

2024-12-29 17:52 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/nuclei.py
> +        info = {
fixed

2024-12-29 17:52 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/nuclei.py
> +    if "rce" in tags or "sqli" in tags or "xss" in tags or "injection" in tags:
fixed

2024-12-29 17:53 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/openvas.py
> +            cves_str += i + " "
fixed

2024-12-30 00:10 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/nuclei.py
> +    if "rce" in tags or "sqli" in tags or "xss" in tags or "injection" in tags:
fixed

2024-12-30 01:58 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +        tokens_key = key.split("_")
fixed

2024-12-30 01:58 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +    for key in applications:
fixed

2024-12-30 01:58 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/openvas.py
> +        if key not in openvas_qod_cve:
fixed

2024-12-30 02:05 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +    inverted_dict = dict(organized_grouping)
fixed

2024-12-30 02:05 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +                    info_to_store = file_name + " - " + entry["file"]
fixed

2024-12-30 02:06 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +                    category_subcategory = category + "_" + subcategory
fixed

2024-12-31 00:42 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +            problems[cves_key][category_subcategory][what_is_detected] = {}
I don't know if this solution is good because I'm redefining the entire dictionary . I honestly don't know if this is the most efficient way to do this, but it seemed intuitive to group the files this way (group by CVE, then Category and Subcategory, What is detected and finally the Application)

2024-12-31 01:22 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +    with open("./results/grouped_scripts.json", "w") as f:
I added a description informing about it, I refactor this path to create the 'results' folder if not exists, but the point of the 'hardcoded' output is to be a fixed output. I can ask the user a path to store, but i fear that maybe the script will have to many parameters (because I am storing more than 1 file)

2024-12-31 01:27 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +                    # if there is no CVE, it is stored as an empty string
is just to add one element on the list, so i can iterate over the empty list (now the empty string exists)

2024-12-31 02:00 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +                    info = classification_info_extracted
fixed

2024-12-31 02:00 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/nuclei.py
> +NUCLEI_TAGS_REGEX = re.compile(r"tags:\s*(?P<tags>[\w,\-]+)")
fixed

2024-12-31 02:01 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +                    return key
fixed

2024-12-31 02:01 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +    for cves_key in cves:
fixed

2024-12-31 02:01 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +            errors_LLM.append(info_to_store)
fixed

2024-12-31 02:01 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +        CHECK_IF_APPLICATION_NAME_IS_TOO_LONG = len(filtered_tokens_application)
my bad. Fixed

2024-12-31 02:01 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +    info_to_store: str,
fixed

2024-12-31 02:01 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +                for entry in data[scan_app]:
fixed

2025-01-01 14:25 UTC, cunha requested changes
* Please apply docstring conventions to module and function docstrings in all files.

* Further improve type annotations, it's one of the best ways to make code self-documenting. Try to specity the contained types in tuples, lists, and dictionaries; if the contained type is too complex, use `typing.Any` instead of leaving the contained types unspecified.

2025-01-01 14:25 UTC, cunha commented on LLM_classification_and_grouping/distributed_classification.py
> +    return results
This is better, but a `dataclass_json` is likely just a Copilot prompt away...

2025-01-01 14:25 UTC, cunha commented on LLM_classification_and_grouping/README.md
> +` python3 distributed_classification.py --<SCANNER_NAME> <PATH_TO_SCANNER_FILES>  --output <OUTPUT_NAME> --initialRange INITIAL_RANGE --finalRange FINAL_RANGE --ip_port <LLM_IP_PORT> `
This should be a single, multi-line code block (with one pair of triple-quotes). Specify `bash` as the language.

2025-01-01 14:25 UTC, cunha commented on LLM_classification/README.md
> +- ```SCANNER``` is one of the following options: nmap, openvas, nuclei, metasploit.
Understood. In this case please change the command-line explanation to something like:

`python3 distributed_classification.py <--nmap|--openvas|--nuclei|--metasploit> <path_to_scanner_files> --output <output_name> --initialRange INITIAL_RANGE --finalRange FINAL_RANGE --ip_port <LLM_ip_port>`

2025-01-01 14:25 UTC, cunha commented on LLM_classification/constants.py
> +"""
Thanks; please apply similar changes to the other module and function docstrings too.

2025-01-01 14:25 UTC, cunha commented on LLM_classification_and_grouping/requirements.txt
> +dataclasses
These are part of the standard library.

2025-01-01 14:25 UTC, cunha commented on LLM_classification_and_grouping/aux/nuclei.py
> +        return []
Please try to specify the contained types in the `yaml_data` parameter, in the return value, and avoid blank `except` clauses.  Our objective is to make the code self-documenting, and these are our first line of defense.

2025-01-01 14:25 UTC, cunha commented on LLM_classification_and_grouping/aux/nmap.py
> +    elif DOS_CATEGORY in categorie:
replace all `s/categorie/category`.

2025-01-01 14:25 UTC, cunha commented on LLM_classification_and_grouping/aux/nmap.py
> +    if BRUTE_FORCE_CATEGORY in categorie:
Why are we using `in` here? Are we searching for a substring inside `categorie`? Should we be using `==` instead?

2025-01-01 14:25 UTC, cunha commented on LLM_classification_and_grouping/aux/nmap.py
> +        any(intrusive in categorie for intrusive in INTRUSIVE_CATEGORIES)
Could this be `categorie in INTRUSIVE_CATEGORIES`? Works if we're just doing exact matches.

2025-01-01 14:25 UTC, cunha commented on LLM_classification_and_grouping/aux/metasploit.py
> +from dataclasses_json import dataclass_json
Check what the convention is. I think docstrings come first in a module, even before the imports... likely not between imports like here.

2025-01-02 21:53 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +                            file_content = read_file_with_fallback(script_name)
I will fix the ID, but to be honest i dont know how to avoid the 5-loop. In practice, the code is not O(n^5), because there is no much intersection between the tools for each CVE, so there is just a few options for What is Detected (or just one option), and just a few files that catch the vulnerability (or just one file).

2025-01-02 23:06 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +                    # if there is no CVE, it is stored as an empty string
the problem is that i use the CVE as a key, so i need to handle the CVE == [ ]. I cant just ignore it or catch this with another approach, because I need to use something as a key to the dict

2025-01-03 00:07 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/nmap.py
> +    if BRUTE_FORCE_CATEGORY in categorie:
the 'categorie' (I renamed the variable now) is a string with all categories from the script. So I use " in " because I am checking if , for example, the BRUTE_FORCE_CATEGORY is one of the elements in 'categorie'

2025-01-03 00:08 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/metasploit.py
> +from dataclasses_json import dataclass_json
fixed

2025-01-03 00:11 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/nmap.py
> +        any(intrusive in categorie for intrusive in INTRUSIVE_CATEGORIES)
I improved this code, 'categorie' is now renamed. It represents all categories in nmap script

2025-01-03 00:11 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/nmap.py
> +    elif DOS_CATEGORY in categorie:
fixed

2025-01-03 00:34 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/nuclei.py
> +        return []
fixed

2025-01-03 00:34 UTC, Francisco-aragao commented on LLM_classification_and_grouping/requirements.txt
> +dataclasses
fixed

2025-01-03 00:34 UTC, Francisco-aragao commented on LLM_classification_and_grouping/README.md
> +` python3 distributed_classification.py --<SCANNER_NAME> <PATH_TO_SCANNER_FILES>  --output <OUTPUT_NAME> --initialRange INITIAL_RANGE --finalRange FINAL_RANGE --ip_port <LLM_IP_PORT> `
fixed

2025-01-03 00:35 UTC, Francisco-aragao commented on LLM_classification_and_grouping/create_problems.py
> +                        except:
fixed -> not reading file again

2025-01-03 00:35 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/openvas.py
> +        "vuldetect": file_vuldetect,
fixed, thanks

2025-01-03 00:35 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/openvas.py
> +            openvas_qod_cve[key].append(openvas_file)
fixed

2025-01-03 00:35 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/openvas.py
> +class CVE_QOD_Key:
fixed

2025-01-03 00:36 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/openvas.py
> +    openvas_qod_cve: dict = {}
I am not using pathlib.Path because is not converted directly to str, so I need to use Path and then convert to str all the time ... But i tried to improve the types

2025-01-03 00:36 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/openvas.py
> +    qod_type: str
improved the names

2025-01-07 13:28 UTC, cunha reviewed
> the 'categorie' (I renamed the variable now) is a string with all categories from the script. So I use " in " because I am checking if , for example, the BRUTE_FORCE_CATEGORY is one of the elements in 'categorie' 

Understood, but then the `all_script_catetogies` variable should be `list[str]` or `set[str]`. It's somewhat confusing to pass multiple categories in a single string (for example, are you separating them with commas?).

2025-01-07 13:29 UTC, cunha commented on LLM_classification_and_grouping/aux/nmap.py
> +    if BRUTE_FORCE_CATEGORY in categorie:
Understood, but then the `all_script_catetogies` variable should be `list[str]` or `set[str]`. It's somewhat confusing to pass multiple categories in a single string (for example, are you separating them with commas?).

2025-01-08 01:37 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/nuclei.py
> +        return []
fixed

2025-01-08 01:37 UTC, Francisco-aragao commented on LLM_classification_and_grouping/aux/nmap.py
> +    if BRUTE_FORCE_CATEGORY in categorie:
fixed, now I am using a list instead of a string

2025-05-05 20:59 UTC, cunha approved these changes

2025-05-28 19:05 UTC, merged