Refactored BERT scripts for orgs and CVEs classification
TopologyMapping/network-security pull request #51
Opened 2024-12-25 20:39 UTC by probablygab

Main changes:

- Split scripts into two files, one for each classification.
- Add configuration classification for CVEs.
- Added README with full installation instructions, examples and output formats.

2024-12-29 00:45 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +    for word in tokens:
this seems to be iterating over lines; am i missing something?

2024-12-29 00:50 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +    hypothesis = "This list of sequences is from a {} webpage."
list of sequences? seems like we will have just one sequence or list? am i missing something?

2024-12-29 00:50 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +    sequence = f"{'; '.join(w for w in sortedWordsEn)}"
is the f-string achieving anything here?

2024-12-29 00:52 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +    - First try with the 15 most common words in the webpage.
Why do we use only the 15 most common words?

2024-12-29 00:53 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +        hypothesis = "This webpage title is from a {} webpage."
Should we explicitly mention the org too in the prompt? Or maybe adjust the prompt depending on what data item is available?

2024-12-29 00:54 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +        hypothesis = "These hostnames are from a {} webpage."
Should we instead pile up words from the page, title, org, and hostnames in attempting to do the classification (instead of discarding the previous data if it didn't lead to a classification)?

2024-12-29 00:57 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +            if isFileCompressed:
We can remove this `if` if we open the (BZ2 or JSON) file above, and then iterate over lines.

2024-12-29 00:58 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +            data = bz2.open(file.path, "rt")
So the BZ2 file is one-line-per-object, and the plain text JSON file is a list that we load all at once? Loading everything at once could be problamatic depending on the size of the file. It would be better to have one-line-per-object in both cases and then iterate over lines below.

2024-12-29 01:00 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +            shodanId: str | None = getNestedFieldData(scan, "_shodan.id")
Is this the same as the meta-id available in Delta Lake land? We should make sure that we have a common key so we can join the org classifications with the votes and Shodan information on the Website's database.

2024-12-29 13:15 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-cves.py
> +    "active in default configuration.",
```suggestion
    "active in the default configuration.",
```

2024-12-29 13:16 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-cves.py
> +    "active in an unknown configuration, i.e. no mention of which configuration is affected.",
```suggestion
    "active in an unknown configuration, i.e., no mention of which configuration is affected.",
```

2024-12-29 13:18 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-cves.py
> +                except:
```suggestion
                except KeyError:
```

Or is it something else?

2024-12-29 13:21 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-cves.py
> +                # In other words, the oldest CVE is processed first and the newest is processed last.
If updates are very common, we could consider processing the most recent CVEs first, and then *skipping* the older ones to avoid running the same CVE through the classifier multiple times.

2024-12-29 13:26 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-cves.py
> +                seenCves[id] = (
The type annotation for the return value is wrong. This entry is very complex, it would benefit from being stored in a `dataclass` (with `json_dataclass` attached for JSON exports). The idea below is not the greatest, but would work as self-documenting:

```python
@dataclass_json
@dataclass
class CVEClassification:
  vulnerability_label2score: dict[str, float]
  configuration_label2score: dict[str, float]
```

2024-12-29 13:43 UTC, cunha commented on info-llm-speed-lab/README.md
> +After the first cmake you should get the following output:
A lot of the output is pasted verbatim in the README, but this is potentially distracting. If there is a specific bit of output that is relevant (e.g., something the user needs to check), then mention just that specific thing; likely in text form, as the output itself may change over time.

2024-12-29 13:44 UTC, cunha commented on info-llm-speed-lab/README.md
> +After the first cmake you should get the following output:
(There are some other large chunks of output elsewhere in the README that we could prune.)

2024-12-29 13:47 UTC, cunha requested changes
Minor suggestions inside.

2024-12-29 18:06 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +    for word in tokens:
It is a consequence of the return type of extractTextFromHtml. In retrospect, it is not very efficient nor elegant. I have updated both functions.

2024-12-29 18:09 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +    sequence = f"{'; '.join(w for w in sortedWordsEn)}"
Nope, it is likely an artifact from experimenting. Removed.

2024-12-29 18:19 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +    hypothesis = "This list of sequences is from a {} webpage."
Well, to be pedantic, even though I named the function bag of words, it is more like a bag of sentences.

This way we won't lose context from sentences in the webpage. If we have a sentence "2017 © Rede Latino-Americana de Justiça de Transição" (actual sentence from a webpage btw). Separating it into words would lead to a loss of context.

I might rename all functions to bag of sentences or just don't use bag at all and just call it most common sentences. I think the latter is more clear.

It is important to separate them using semicolons, because not every sentence is cohesive when put next to each other.

2024-12-29 18:23 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +    - First try with the 15 most common words in the webpage.
As I said earlier, this should be 15 more common sentences. There is no particular reason why it is 15, but I think we should be limiting either way so the model will focus on the most common sentences and forget less common and not particularly interesting sentences like: "about us", "contact" and so on.

I think it is a good idea to use percentages, "First try with the 50% more common sentences" is more clear and agnostic when it comes to the number of sentences.

2024-12-29 18:41 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +        hypothesis = "This webpage title is from a {} webpage."
I think dinamically adjusting is better. Updated.

2024-12-29 18:49 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +        hypothesis = "These hostnames are from a {} webpage."
Honestly I have no idea, when I print the results of each step, if the sequence step fails, then the sentences were actual garbage, like, very few sentences with minimal words.

This happens when Shodan doesn't have a good webpage capture for that page, like we noticed happening on Shogun.

Same goes for org and webpageTitle, when the classification fails, they are usually empty or one of them has just one nonsensical word.

This was the main idea behind discarding them, they are usually not that good at all if the classification fails. This is also why the sentence classification is the first, it is the most likely to yield a good result, if that fails, then the rest is a try to salvage the classification. Basically, the other tries are not supposed to yield good results, but rather, good enough results.

2024-12-29 18:50 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +    - First try with the 15 most common words in the webpage.
Updated as per my own suggestion.

2024-12-29 18:54 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +            shodanId: str | None = getNestedFieldData(scan, "_shodan.id")
I believe Shodan ID is not the same, they are using Meta IDs. 

Come to think of it, I have no idea how Meta ID is calculated to implement it here. Though, Shodan ID is unique, we have tested it before.

I will have a look at Delta Lake Land.

2024-12-29 18:54 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-cves.py
> +    "active in default configuration.",
Fair enough

2024-12-29 18:58 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-cves.py
> +                except:
That is it, I also updated the two getters a few lines below.

2024-12-29 19:06 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +            data = bz2.open(file.path, "rt")
The .json file is there for compatibility. All Shodan scans (when retrieved by the cron job) are stored as .json.bz2. 

The bz2 library is arguably well optimized and won't read the whole file into memory, same goes for zipfile in classify-cves.py.

You are correct that plain JSON file may be a problem, but as I said above, it is not supposed to be used most of the time. Decompressing the .json.bz2 files to .json is a waste of space and is not necessary, since the script already supports these files natively.

The idea is to support small .json files, i.e. a slice of a larger .json.bz2 file for experimenting.

2024-12-29 19:14 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-cves.py
> +                # In other words, the oldest CVE is processed first and the newest is processed last.
This is smart. Updated.

2024-12-29 19:34 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-cves.py
> +                seenCves[id] = (
Oh right, I forgot to update the return type.

2024-12-29 19:47 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-cves.py
> +                except:
EDIT: not quite, if state is not found, then the other fields might have different exceptions. I have left it as except only.

2024-12-29 20:09 UTC, probablygab commented on info-llm-speed-lab/README.md
> +After the first cmake you should get the following output:
I mean, the ideia was to guide the user, the output examples should be reassuring: "I followed step X and got the same output"

I will prune some of them, keep the small ones and mention specific things, like you suggested.

2024-12-29 21:37 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +            shodanId: str | None = getNestedFieldData(scan, "_shodan.id")
UPDATE: Pep said using shodan_id works fine. This field is available in Delta Lake for correlation.

2025-01-01 14:31 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-cves.py
> +                except:
Maybe `except KeyError, IndexError`? There doesn't seem to be anything else going on here... unless we have overloaded `__getitem__` throwing unexpected exceptions around.

2025-01-01 14:33 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +        hypothesis = "These hostnames are from a {} webpage."
Makes sense; in this case I agree it's better to not carry the trash over. Copy this into a comment to capture the logic here (as other people might get the same bad idea).

2025-01-01 14:36 UTC, cunha commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +            data = bz2.open(file.path, "rt")
Makes sense, but my question is about the files having different formats. It seems like the BZ2 files is one-line-per-object:

```
{object1}
{object2}
{object3}
...
```

While the JSON file is a list-with-objects:

```
[
  {object1},
  {object2},
  {object3},
  ...
]
```

If this is the case, just compressing a JSON file will not work as the BZ2 code path does not seem to work for list-with-objects.

2025-01-01 14:38 UTC, cunha commented on scripts/classify-orgs-and-cves/requirements.txt
> +dataclasses-json
Most of these are in the standard library and need not be part of `requirements.txt`.

2025-01-01 14:40 UTC, cunha requested changes
Just some back-and-fourth on the responses.

2025-01-02 19:53 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +        hypothesis = "These hostnames are from a {} webpage."
Added a NOTE comment at the start of the function.

2025-01-02 20:15 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-orgs.py
> +            data = bz2.open(file.path, "rt")
You are right, just ran `bzcat BR.20240720.json.bz2 | head -3` and the scans are one per line. 

In this case, I wouldn't want to clutter the code with some shenanigans to deal seamlessly with different formats at runtime. Moreover, I don't have any control regarding what the user will use as input.

So, for now, I have decided to add a short section in the README detailing the expected input format following your template. I also added a disclaimer about using large JSON files.

2025-01-02 20:27 UTC, probablygab commented on scripts/classify-orgs-and-cves/classify-cves.py
> +                except:
Second exception is actually a TypeError, so `except (KeyError, TypeError)` works like a charm now.

2025-01-02 20:31 UTC, probablygab commented on scripts/classify-orgs-and-cves/requirements.txt
> +dataclasses-json
Right, I have updated this file per the standard library here: https://docs.python.org/3/library/index.html

2025-01-07 13:46 UTC, merged